### ISSUE TITLE
Code doesn't build with latest rand 0.6.5

### ISSUE THREAD

**Issue by eclipseo** [expenses/line_drawing#4]
```
error[E0432]: unresolved import `self::rand::distributions::range`
 --> src/fuzzing.rs:6:32
  |
6 | use self::rand::distributions::range::SampleRange;
  |                                ^^^^^ could not find `range` in `distributions`

warning: use of deprecated item 'fuzzing::rand::ThreadRng': import with rand::prelude::* or rand::rngs::ThreadRng instead
  --> src/fuzzing.rs:19:30
   |
19 | fn random_point<T>(rng: &mut rand::ThreadRng, range: T) -> Point<T>
   |                              ^^^^^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default

warning: use of deprecated item 'fuzzing::rand::ThreadRng': import with rand::prelude::* or rand::rngs::ThreadRng instead
  --> src/fuzzing.rs:26:30
   |
26 | fn random_voxel<T>(rng: &mut rand::ThreadRng, range: T) -> Voxel<T>
   |                              ^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by expenses** [comment]
I believe this is fixed now?
